languageCode: en-us
languageName: English
displayName: EN
isoCode: en
weight: 1
rtl: false
title: David Simão
# logo: img/logo.png
description: Welcome to the jungle
copyright: No rights reserved
dateFormat: January 2, 2006

author:
  name: David Simão
  image: img/profilepic.png
  headline: Engineer, geek, gamer
  bio: Software Engineer
  links:
    - github: "https://github.com/madoke"
    - linkedin: "https://www.linkedin.com/in/davidsimao/"
    - keybase: "https://keybase.io/madoke"
    - goodreads: "https://www.goodreads.com/user/show/151059176-david-simao"
    - pgpkey: "/pgp.txt"
    - ethereum: https://app.ens.domains/name/davidsimao.eth/details
