languageCode: en-us
languageName: English
weight: 1
title: David Simão
copyright: No rights reserved

params:
  description: David Simao's personal profile
  dateFormat: January 2, 2006
  isoCode: en
  displayName: EN
  rtl: false

author:
  name: David Simão
  image: img/profilepic.png
  headline: Engineer, geek, gamer
  bio: Software Engineer
  links:
    - github: "https://github.com/madoke"
    - linkedin: "https://www.linkedin.com/in/davidsimao/"
    - keybase: "https://keybase.io/madoke"
    - goodreads: "https://www.goodreads.com/user/show/151059176-david-simao"
    - pgpkey: "/pgp.txt"
    - ethereum: https://app.ens.domains/name/davidsimao.eth/details
    - solana: https://www.sns.id/domain?domain=davidsimao
