---
main:
  - name: About
    pageRef: about
    weight: 1
  - name: Blog
    url: https://jungle.madoke.org
    weight: 2
  - identifier: github
    pre: github
    url: https://github.com/madoke/madoke.org
    weight: 4

footer: []
