services:
  hugo:
    image: hugomods/hugo:0.121.0
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    expose:
      - 1313
    ports:
      - 1313:1313
    command: hugo server --bind 0.0.0.0 -D